name: CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      
    - name: Print Env
      run: |
        python -c << EOF "
        tag = 'GITHUB_REF'.split('/')[-1]
        print(tag)
        print('__version__ =', tag)
        "
        EOF > version.py
        echo "VERSION"
        cat version.py
